import { RemovalPolicy } from "aws-cdk-lib";

export const devConfig = {
  albOriginDomainName: "origin-dev.tikyuu.click",
  applicationName: "gym-management",
  apiRepositoryEmptyOnDelete: true,
  apiRepositoryRemovalPolicy: RemovalPolicy.DESTROY,
  apiDesiredCount: 1,
  apiTaskCpu: 512,
  apiTaskMemoryMiB: 1024,
  authenticationRemovalPolicy: RemovalPolicy.DESTROY,
  authenticationUserPoolDeletionProtection: false,
  customerAuthDomainName: "auth-dev.tikyuu.click",
  customerOAuthCallbackUrls: [
    "http://localhost:5173/auth/callback",
    "https://dev.tikyuu.click/auth/callback",
  ],
  customerOAuthLogoutUrls: [
    "http://localhost:5173",
    "https://dev.tikyuu.click",
  ],
  customerUserPoolDomainPrefix: "gym-management-dev",
  staffAuthDomainName: "staff-auth-dev.tikyuu.click",
  staffOAuthCallbackUrls: [
    "http://localhost:5173/staff/auth/callback",
    "https://dev.tikyuu.click/staff/auth/callback",
  ],
  staffOAuthLogoutUrls: [
    "http://localhost:5173/staff",
    "https://dev.tikyuu.click/staff",
  ],
  staffUserPoolDomainPrefix: "gym-management-dev-staff",
  systemAdminAuthDomainName: "system-admin-auth-dev.tikyuu.click",
  systemAdminOAuthCallbackUrls: [
    "http://localhost:5173/system-admin/auth/callback",
    "https://dev.tikyuu.click/system-admin/auth/callback",
  ],
  systemAdminOAuthLogoutUrls: [
    "http://localhost:5173/system-admin",
    "https://dev.tikyuu.click/system-admin",
  ],
  systemAdminUserPoolDomainPrefix: "gym-management-dev-system-admin",
  databaseAllocatedStorage: 20,
  databaseAutoMinorVersionUpgrade: true,
  databaseBackupRetentionPeriod: 1,
  databaseDeletionProtection: false,
  databaseEngineVersion: "18.4",
  databaseInstanceIdentifier: "gym-management-dev-postgresql",
  databaseInstanceClass: "db.t4g.micro",
  databaseMaxAllocatedStorage: 50,
  databaseMultiAz: false,
  databasePreferredBackupWindow: "19:00-19:30",
  databasePreferredMaintenanceWindow: "fri:20:00-fri:21:00",
  databaseRemovalPolicy: RemovalPolicy.DESTROY,
  databaseStorageType: "gp3",
  edgeRegion: "us-east-1",
  edgeCertificateSubjectAlternativeNames: [
    "auth-dev.tikyuu.click",
    "staff-auth-dev.tikyuu.click",
    "system-admin-auth-dev.tikyuu.click",
  ],
  frontendDomainName: "dev.tikyuu.click",
  frontendBucketAutoDeleteObjects: true,
  frontendBucketRemovalPolicy: RemovalPolicy.DESTROY,
  frontendBucketVersioned: false,
  environmentName: "dev",
  hostedZoneId: "Z06251752UDDGYJM4C7LL",
  hostedZoneName: "tikyuu.click",
  region: "ap-northeast-1",
  vpcCidr: "10.10.0.0/16",
  publicSubnets: [
    {
      id: "PublicSubnet1",
      name: "public-1a-subnet",
      availabilityZone: "ap-northeast-1a",
      cidrBlock: "10.10.1.0/24",
    },
    {
      id: "PublicSubnet2",
      name: "public-1c-subnet",
      availabilityZone: "ap-northeast-1c",
      cidrBlock: "10.10.2.0/24",
    },
  ],
  privateIngressSubnets: [
    {
      id: "PrivateIngressSubnet1",
      name: "private-ingress-1a-subnet",
      availabilityZone: "ap-northeast-1a",
      cidrBlock: "10.10.11.0/24",
    },
    {
      id: "PrivateIngressSubnet2",
      name: "private-ingress-1c-subnet",
      availabilityZone: "ap-northeast-1c",
      cidrBlock: "10.10.12.0/24",
    },
  ],
  applicationSubnets: [
    {
      id: "ApplicationSubnet1",
      name: "private-application-1a-subnet",
      availabilityZone: "ap-northeast-1a",
      cidrBlock: "10.10.21.0/24",
    },
    {
      id: "ApplicationSubnet2",
      name: "private-application-1c-subnet",
      availabilityZone: "ap-northeast-1c",
      cidrBlock: "10.10.22.0/24",
    },
  ],
  databaseSubnets: [
    {
      id: "DatabaseSubnet1",
      name: "private-database-1a-subnet",
      availabilityZone: "ap-northeast-1a",
      cidrBlock: "10.10.31.0/24",
    },
    {
      id: "DatabaseSubnet2",
      name: "private-database-1c-subnet",
      availabilityZone: "ap-northeast-1c",
      cidrBlock: "10.10.32.0/24",
    },
  ],
};
