import { RemovalPolicy } from "aws-cdk-lib";

export const devConfig = {
  applicationName: "gym-management",
  apiRepositoryEmptyOnDelete: true,
  apiRepositoryRemovalPolicy: RemovalPolicy.DESTROY,
  apiDesiredCount: 1,
  apiTaskCpu: 512,
  apiTaskMemoryMiB: 1024,
  authenticationRemovalPolicy: RemovalPolicy.DESTROY,
  authenticationUserPoolDeletionProtection: false,
  customerOAuthCallbackUrls: ["http://localhost:5173/auth/callback"],
  customerOAuthLogoutUrls: ["http://localhost:5173"],
  customerUserPoolDomainPrefix: "gym-management-dev",
  staffOAuthCallbackUrls: ["http://localhost:5173/staff/auth/callback"],
  staffOAuthLogoutUrls: ["http://localhost:5173/staff"],
  staffUserPoolDomainPrefix: "gym-management-dev-staff",
  systemAdminOAuthCallbackUrls: [
    "http://localhost:5173/system-admin/auth/callback",
  ],
  systemAdminOAuthLogoutUrls: ["http://localhost:5173/system-admin"],
  systemAdminUserPoolDomainPrefix: "gym-management-dev-system-admin",
  databaseAllocatedStorage: 20,
  databaseAutoMinorVersionUpgrade: true,
  databaseBackupRetentionPeriod: 1,
  databaseDeletionProtection: false,
  databaseEngineVersion: "18.4",
  databaseInstanceClass: "db.t4g.micro",
  databaseMaxAllocatedStorage: 50,
  databaseMultiAz: false,
  databasePreferredBackupWindow: "19:00-19:30",
  databasePreferredMaintenanceWindow: "fri:20:00-fri:21:00",
  databaseRemovalPolicy: RemovalPolicy.DESTROY,
  databaseStorageType: "gp3",
  frontendBucketAutoDeleteObjects: true,
  frontendBucketRemovalPolicy: RemovalPolicy.DESTROY,
  frontendBucketVersioned: false,
  environmentName: "dev",
  region: "ap-northeast-1",
  vpcCidr: "10.10.0.0/16",
  publicSubnets: [
    {
      id: "PublicSubnet1",
      name: "public-1a-subnet",
      availabilityZone: "ap-northeast-1a",
      cidrBlock: "10.10.1.0/24",
    },
    {
      id: "PublicSubnet2",
      name: "public-1c-subnet",
      availabilityZone: "ap-northeast-1c",
      cidrBlock: "10.10.2.0/24",
    },
  ],
  privateIngressSubnets: [
    {
      id: "PrivateIngressSubnet1",
      name: "private-ingress-1a-subnet",
      availabilityZone: "ap-northeast-1a",
      cidrBlock: "10.10.11.0/24",
    },
    {
      id: "PrivateIngressSubnet2",
      name: "private-ingress-1c-subnet",
      availabilityZone: "ap-northeast-1c",
      cidrBlock: "10.10.12.0/24",
    },
  ],
  applicationSubnets: [
    {
      id: "ApplicationSubnet1",
      name: "private-application-1a-subnet",
      availabilityZone: "ap-northeast-1a",
      cidrBlock: "10.10.21.0/24",
    },
    {
      id: "ApplicationSubnet2",
      name: "private-application-1c-subnet",
      availabilityZone: "ap-northeast-1c",
      cidrBlock: "10.10.22.0/24",
    },
  ],
  databaseSubnets: [
    {
      id: "DatabaseSubnet1",
      name: "private-database-1a-subnet",
      availabilityZone: "ap-northeast-1a",
      cidrBlock: "10.10.31.0/24",
    },
    {
      id: "DatabaseSubnet2",
      name: "private-database-1c-subnet",
      availabilityZone: "ap-northeast-1c",
      cidrBlock: "10.10.32.0/24",
    },
  ],
};
